---
- hosts: master
  tasks:

  - name: deregister Antrea interworking
    kubernetes.core.k8s:
      state: present
      src: "{{ vars.base_path }}/{{ vars.antrea_deregister_job_yaml }}"
    when: vars.cni_kind == "antrea"

  - name: Waiting for deregister pod to complete  ...
    shell: kubectl get pods -n vmware-system-antrea | grep deregister
    register: get_pods
    until: ' "Completed" in get_pods.stdout'
    retries: 10
    delay: 10
    when: vars.cni_kind == "antrea"

  - name: Running NSX policy cleanup script...
    command: 'python3 {{ vars.base_path }}/ncp/nsx_policy_cleanup.py --mgr-ip="{{ vars.nsx_mgr_ip }}" -u "{{ vars.nsx_username }}" -p "{{ vars.nsx_password }}" -c "{{ vars.nsx_cluster }}" --top-tier-router-id="{{ vars.nsx_top_tier_router_id }}" --no-warning -r'
    register: cleanup_output
    until: '"No top tier-1 router to be deleted" in cleanup_output.stdout'
    retries: 1
    delay: 5
    when: vars.cni_kind == "ncp"
