---
- hosts: master
  tasks:
  
  - name: Create avi-system namespace for ako
    kubernetes.core.k8s:
      name: avi-system
      api_version: v1
      kind: Namespace
      state: present

  - name: install AKO
    kubernetes.core.helm:
      release_name: ako
      chart_ref: https://projects.registry.vmware.com/chartrepo/ako
      release_state: present
      release_namespace: avi-system
      values_files: "{{ vars.base_path }}/{{ vars.ako_yaml }}"
      chart_version: "{{ vars.ako_version }}" 
      release_values:
        generate-name: true
        set:
          ControllerSettings:
            controllerHost: "{{ avi_controller }}" 
          avicredentials:
            username: "{{ avi_user }}"
            password: "{{ avi_password }}"
          AKOSettings:
            primaryInstance: true

  - name: Waiting for ako pod to come up...
    shell: kubectl get pods -n avi-system 
    register: get_pods
    until: ' "Running" in get_pods.stdout'
    retries: 10
    delay: 5
