---
- hosts: master
  tasks:

  - name: install CNI
    kubernetes.core.k8s:
      state: present
      src: "{{ vars.base_path }}/{{ vars.cni_yaml }}"

  # often coredns deployment needs to be restarted with ncp
  - name: Restarting coredns deployment
    shell: kubectl rollout restart deployment coredns -n kube-system
    when: vars.cni_kind == "ncp"

  - name: Waiting for pods to come up...
    shell: kubectl get pods -n kube-system -o json
    register: kubectl_get_pods
    until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
    retries: 10
    delay: 10
