---
- hosts: master
  tasks:
  - name: install CNI
    kubernetes.core.k8s:
      state: present
      src: "{{ vars.base_path }}/{{ vars.cni_yaml }}"

  - name: waiting 5 sec...
    wait_for:
      timeout: 5
  
  - name: Waiting for pods to come up...
    shell: kubectl get pods -n kube-system -o json
    register: get_pods
    until: get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
    retries: 10
    delay: 10
