---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: reset kubeadm
    shell: kubeadm reset -f

  - name: delete CNI directory
    file: 
      state: absent
      path: "{{ item }}"
    with_items: 
      - /etc/cni/net.d/
      - /etc/kubernetes/

  - name: delete .kube directory
    become: yes
    become_user: ubuntu
    file:
      path: $HOME/.kube
      state: absent
