---
- hosts: master
  become: yes
  gather_facts: false
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  gather_facts: false
  tasks:
  - name: join cluster
    shell: "{{ hostvars['master'].join_command }} --ignore-preflight-errors all"

- hosts: master
  gather_facts: false
  tasks:
  - name: waiting for workers to join the cluster
    shell: kubectl get nodes 
    register: nodes
    until: '" NotReady " not in nodes.stdout'
    retries: 10
    delay: 10