---
- hosts: master
  tasks:

  - name: patch ConfigMap to delete ako created objects from Avi controller 
    kubernetes.core.k8s:
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: avi-k8s-config
          namespace: avi-system
        data:
          deleteConfig: "true"
      continue_on_error: false

